### ISSUE TITLE
Consider tar_option_set(package = getNamespace("dftTrafficCounts"))

### ISSUE THREAD

**Issue by wlandau** [ITSLeeds/dftTrafficCounts#1]
This will allow `targets` to watch your package's R code and automatically rebuild targets with the functions change.

**Comment by Robinlovelace** [comment]
Just adding this now, good suggestion. Quick question @wlandau, will the target rebuild when I edit files in the package, or only after I reinstall it?

**Comment by Robinlovelace** [comment]
Heads-up, I tried that but it seems to fail when I run the following commands (note the commented out lines were what I had before):

```
# Set target-specific options such as packages.
# pkgs = c("dplyr", "dftTrafficCounts")
pkgs = c("dplyr")
# tar_option_set(packages = pkgs)
tar_option_set(package = getNamespace("dftTrafficCounts"))
```

**Comment by Robinlovelace** [comment]
That gave this error message:

```
> targets::tar_make()
Error : packages in tar_option_set() must be character.
Error: callr subprocess failed: packages in tar_option_set() must be character.
Type .Last.error.trace to see where the error occured
```

**Comment by Robinlovelace** [comment]
OK I think this fixes it...

```
tar_option_set(packages = pkgs, envir = getNamespace("dftTrafficCounts"))

```
