### ISSUE TITLE
Consider tar_target(format = "url")

### ISSUE THREAD

**Issue by wlandau** [ITSLeeds/dftTrafficCounts#2]
This will allow `targets` to automatically decide when to re-download remote files. Your pipeline would look like this:

```r
tar_pipeline(
  tar_target(url, "http://data.dft.gov.uk/road-traffic/dft_traffic_counts_raw_counts.zip", format = "url"),
  tar_target(data, dtc_import(u = url)),
  tar_target(summary_dft, summ(data)),
  tar_target(summary_mode, summary_dft_mode_year(data)),
  tar_render(readme, "README.Rmd", output_format = "github_document", output_file = "README.md")
)
```

Both http://data.dft.gov.uk/road-traffic/dft_traffic_counts_raw_counts.zip and https://dft-statistics.s3.amazonaws.com/road-traffic/downloads/aadf/count_point_id/dft_aadf_count_point_id_74816.csv have valid ETags and Last-Modified time stamps, so `targets` can handle this.

**Comment by Robinlovelace** [comment]
Great suggestion. Implemented!
